### ISSUE TITLE
Ocveralls should not be built with bisect :)

### ISSUE THREAD

**Issue by simonjbeaumont** [sagotch/ocveralls#11]
I think that ocveralls is shipping linked with bisect itself. This is really annoying because it means that executing ocveralls itself is producing bisect files. Worse, these cannot be used because we don't have the cmp files.

It means we can't run it more than once.

```
$ ocveralls --repo_token dummy --prefix _build bisect*.out --output dump.json                                                              
$ echo $?
0
$ ocveralls --repo_token dummy --prefix _build bisect*.out --output dump.json
Fatal error: exception Sys_error("_build/src/ocveralls.cmp: No such file or directory")
$ ls bisect000*
bisect0001.out  bisect0002.out
$ cat bisect0002.out                                                                                                                   
BISECT-RTD?????A@????L                    ?0src/ocveralls.m@@@@@@@@@@@@@@@@@@@@AA@@@@@@@@AAA@AAA@AAAAAAAAAAAAAAA@@AAAAAAAAAAAAAAAAAA@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@?4src/ocverallsJSON.ml??2src/ocverallsCI.ml?A?6src/ocverallsBisect.m?b?         ??                                              JJ      JJJ%JJJJJJAA@@@@@@@@@A@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by sagotch** [comment]
The fact that ocveralls produces bisect file is due to a hook in bisect lib when opening a module, it is a known _bug_ and there is not much I can do except copying bisect modules and modifying them. I would prefer to avoid that but it should actually be an easy fix.

I am not sure about that issue being annoying enough to merge bisect's file into ocveralls.

In real world, do you really run ocveralls twice without any cleaning? Typical use case is to run ocveralls on Travis (or any CI service), so fake bisects files are supposed to be removed between 2 runs.

See https://github.com/sagotch/ocveralls#know-bugs for another way to _fix_ it. Does this solution satisfy you ?

**Comment by simonjbeaumont** [comment]
Sorry for the delayed response. I understand now and should have checked the known issues section. You're right in most use cases you wouldn't want to run it twice. I was hitting this when trying to do some debugging and using the --json output argument.
