### ISSUE TITLE
Array index out-of-bounds when combining *.out files from multiple runs

### ISSUE THREAD

**Issue by djs55** [sagotch/ocveralls#4]
I sometimes find that bisect runs of the same program will include count vectors of different lengths for the same file, triggering an array index exception in ocveralls.

Recompiling with -g gives me

```
$ OCAMLRUNPARAM=b ~/sagotch/ocveralls/ocveralls.native --prefix _build _build/xenvm.coverage0001.out _build/xenvm.coverage0002.out
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "src/ocverallsBisect.ml", line 73, characters 49-55
Called from file "array.ml", line 93, characters 21-43
Called from file "list.ml", line 84, characters 24-34
Called from file "src/ocverallsBisect.ml", line 83, characters 8-60
Called from file "list.ml", line 55, characters 20-23
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "src/ocveralls.ml", line 60, characters 4-29
```

Is zero-padding short vectors the right thing to do? I'll submit a pull request for your review.

**Comment by sagotch** [comment]
Thank you for this bug report and this patch. :+1:

I mailed the bisect author for details about this behavior, in order to be sure to understand it.

I am waiting for him to answer before merging you're PR.

Note : In order not to miss information, the array on which is applied the `mapi` function should be
the longest one.
