### ISSUE TITLE
Ocveralls and Bisect disagree on coverage metrics.

### ISSUE THREAD

**Issue by simonjbeaumont** [sagotch/ocveralls#6]
My scripts generate a single bisect file:

```
$ ls bisect*
bisect0001.out
```

If I run `bisect-report` I get these values for the coverage:

```
$ bisect-report -I _build bisect0001.out -text report
$ egrep "Summary|File|total" report
Summary:
- total: 353/374 (94.39%)
File 'bindings/ffi_bindings.ml':
- total: 161/161 (100.00%)
File 'lib/ffi_generated.ml':
- total: 35/37 (94.59%)
File 'lib/ffi_generated_types.ml':
- total: 55/62 (88.71%)
File 'lib/pci.ml':
- total: 57/67 (85.07%)
File 'lib_test/test_pci.ml':
- total: 45/47 (95.74%)
```

But when I use ocveralls it generates very different metrics on this build.
Here is the commit SHA for the above:

```
$ git rev-parse HEAD
e58ecc98ca565a963ec92718e9945b4b84459640
```

And here is the corresponding build on coveralls.io (you can see it has the
same git SHA):

https://coveralls.io/builds/2651693

Here it thinks, for example, that the coverage of `lib/pci.ml` is just 20% but the bisect-report says it is 85%. Also just by visual inspection it is clear that the lines are being marked wrong. For example, the [lines marked in `lib_test/test_pci.ml`](https://coveralls.io/builds/2651693/source?filename=lib_test%2Ftest_pci.ml) are clearly wrong. These lines are clearly executed by the OUnit framework.

This was generated using:

```
$ ocveralls --prefix _build bisect* --send
```

I've used `--repo_token /dev/null --output ocveralls_dump` to collect the
output and uploaded that, the bisect report and the bisect file to gist:

https://gist.github.com/simonjbeaumont/85fca139e173b7573763

Any ideas?

**Comment by sagotch** [comment]
Thank you for reporting, I am looking for what is going wrong right now.

**Comment by sagotch** [comment]
After looking into bisect's code in order to compare it with my implementation, I did not find anything here.

I could not run the tests of your package at home. I actually had a 100% failure rate, but some files were missing, I do not remember exactly which ones. Would you have a complete instruction set (including dependencies to install) in order to run your tests? It could be helpful for debugging.

If you want to, you could try using a bisect distribution modified by the original author himself (look at [.travis-si.sh] file). https://github.com/sagotch/ocveralls.sh/tree/master, 

Also, here is the link of this modified version of bisect, if one want to look at it and help me here. The coveralls stuff is done in [report/reportCoveralls.ml{,i}]. See http://sagotch.fr/www/download/bisect-coveralls.tar.gz

I have no time to go deeper now, but I'll try to find the time to fix.

EDIT: I have just sent a mail to Xavier Clerc to know if he would have an idea about what is wrong with my code.

**Comment by simonjbeaumont** [comment]
Hey, thanks for the quick response. I've been poking around myself in `ocverallsBisect.ml` but not got anything yet.

You'll need the following dependencies:

```
opam install ctypes ocamlfind ounit bisect_ppx ocveralls oasis
# on debian-like systems...
apt-get install hwdata libpci-dev
# on redhat-like systems...
yum install hwdata pciutils-devel
```

If you want to build and test then you'll need a Linux box (I've tested on CentOS and Ubunutu (it's working on Travis)) and clone and run the following:

```
./configure --enable-tests
make test
```

These tests should work.

If you want to try the coverage stuff then please remove `trap` line in the `.coverage.sh` script so that it doesn't clean up: https://github.com/simonjbeaumont/ocaml-pci/blob/master/.coverage.sh#L9

Then run

```
bash -ex .coverage.sh
```

This will create a `.coverage/` directory in which the above commands were executed.

I'll take a look at the custom `bisect-report` with the `-coveralls` option as you suggested.

Thanks again,

Si

**Comment by simonjbeaumont** [comment]
I just tried using this patched version of bisect that you host and it has the same behaviour. It seems the logic when using the `-coveralls` flag comes up with a different metric from when using `-text` or `-html`. See https://github.com/simonjbeaumont/ocaml-pci/pull/11.

**Comment by sagotch** [comment]
Very good! Thank you for this new clue.

I will have some time tomorrow morning to compare bisect's modules for reporting coveralls and text / html. The bug will probably be easier to spot than comparing ocverallsBisect with reportText module.

**Comment by rleonid** [comment]
Hi, apologies for the delay (currently traveling).

I'll look into it more fully when I get back, but I have sneaky suspicion that it is `bisect_ppx` related. I'd guess your issue is probably related to this bisect_ppx [issue](https://github.com/rleonid/bisect_ppx/issues/10) which probably stems from this [one](https://github.com/rleonid/bisect_ppx/issues/7). At some point, probably while pulling out the Camlp4 stuff, I broke the reporting tool that ships with the install. My apologies.

When I get back (next week) I'll make it a priority to fix.

**Comment by simonjbeaumont** [comment]
There is no problem with `bisect_ppx` since if I run `bisect-report -html` on the output I get something sensible. I get the right % coverage and the lines highlighted as uncovered are correct since they are in exception handlers that are untested in the unit tests.

Both `bisect-report -html` and the modified `bisect-report -coveralls` operate on the same bisect file.

**Comment by simonjbeaumont** [comment]
Right. Thanks for the tip @rleonid. I made some changes to upload the bisect HTML report to my github pages as part of my travis job and was shocked that even these had different results from when I ran them locally.

However, it turns out that the difference was with the way OUnit2 was forking(?) in that environment leading to incomplete results. I went back and correlated the "wrong" results and noticed that the coverage in the test module made it look always like only one of three of the test cases was being run. It wasn't always the same one but it did always correlate clearly with the coverage results in the library it was testing.

So I solved this gnarly issue with this commit https://github.com/simonjbeaumont/ocaml-pci/commit/19941f44a5ddc746995b749cc11fe5983200484c which _simply_ adds `-runner sequential` to the test suite invocation.

I then enabled `ocveralls --send` again and success! My coverage on coveralls is correct at 95% and it's clear from inspection that it's got the right coverage: https://coveralls.io/builds/2679078.

Therefore I think we can absolve Ocveralls from this problem. I still don't know where this problem with the interaction between bisect_ppx and OUnit lies but I can work around it.

**Comment by sagotch** [comment]
Oh... I just remember now... I had the same issue with Bisect and OUnit running multiple threads.

Glad to know that ocveralls is fine, but I am interested in knowing more about this problem.

**Comment by sagotch** [comment]
You may be intereset by what Xavier Clerc said:

> Si vous utilisez plusieurs threads, il est nécessaire de linker
> avec le module "BisectThread" qui se charge d'ajouter
> l'utilisation d'un verrou aux routines de bisect.
> 
> Attention, comme ce module n'est pas appelé (il enregistre
> seulement un callback), il faut "forcer" son link via l'option
> "-linkall" du compilateur.

For those who are not french speakers: You need to link `BisectThread` module when using multiple threads. As the only action of this module is to register a callbacl, you need to force linking using `-linkall` compiler's option.
